[build]
builder = "nixpacks"
buildCommand = "npm install && npx nx build align-api --configuration=production"

[deploy]
startCommand = "node dist/apps/align-api/main.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
